<?xml version="1.0" encoding="utf-8"?><Database Name="happyCenterBdd" Class="hcBddDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\happyCenterBdd.mdf;Integrated Security=True" SettingsObjectName="HappyCenter.Properties.Settings" SettingsPropertyName="happyCenterBddConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Moniteurs" Member="Moniteurs">
    <Type Name="Moniteurs">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prenom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Activite" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Activites" Member="Activites">
    <Type Name="Activites">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Heure_Debut" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Heure_Fin" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Age_Min" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Age_Max" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Personnes" Member="Personnes">
    <Type Name="Personnes">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prenom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Salles" Member="Salles">
    <Type Name="Salles">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom_Activite" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nom_Moniteur" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Duree_Activite" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Effectif_Max" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>