<?xml version="1.0" encoding="utf-8"?><Database Name="happyCenterBdd" Class="hcBddDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\happyCenterBdd.mdf;Integrated Security=True" SettingsObjectName="HappyCenter.Properties.Settings" SettingsPropertyName="happyCenterBddConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Utilisateurs" Member="Utilisateurs">
    <Type Name="Utilisateurs">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prenom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Activite" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Jour_Activite" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Horaires_Activite" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Association Name="Utilisateurs_Activites" Member="Activites1" ThisKey="Id" OtherKey="Id_Personne" Type="Activites" />
      <Association Name="Activites_Utilisateurs" Member="Activites" ThisKey="Id_Activite" OtherKey="Id" Type="Activites" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Activites" Member="Activites">
    <Type Name="Activites">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Heure_Debut" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Heure_Fin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Age_Min" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Age_Max" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Etat" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Personne" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Activites_Utilisateurs" Member="Utilisateurs" ThisKey="Id" OtherKey="Id_Activite" Type="Utilisateurs" />
      <Association Name="Utilisateurs_Activites" Member="Utilisateurs1" ThisKey="Id_Personne" OtherKey="Id" Type="Utilisateurs" IsForeignKey="true" />
    </Type>
  </Table>
</Database>